# Generated by Django 4.2.1 on 2023-05-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_solicitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='atribut',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='serv',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='unid',
            field=models.TextField(default=''),
        ),
    ]
