# Generated by Django 4.2.1 on 2023-05-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tryacess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tryacess',
            name='password',
        ),
    ]
