# Generated by Django 4.2.1 on 2023-05-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_tryacess_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_attempts',
        ),
    ]
